# Generated by Django 4.1.5 on 2023-02-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dias', models.SmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('jefe', models.CharField(max_length=50)),
                ('domingos', models.SmallIntegerField()),
                ('dias_festivos', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Aprobada', 'Aprobada')], max_length=50)),
            ],
        ),
    ]
