# Generated by Django 4.1.5 on 2023-02-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0005_perfil_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Supervisos', 'Supervisos'), ('Dueño', 'Dueño')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Aprobada', 'Aprobada')], default='Pendiente', max_length=50),
        ),
    ]
