# Generated by Django 4.1.5 on 2023-02-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0007_alter_perfil_image_alter_solicitud_vacaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='users/image_user.png', upload_to='users/'),
        ),
    ]
