# Generated by Django 4.1.5 on 2023-02-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0008_alter_perfil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vigencia_dias_vacaciones_disp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
