# Generated by Django 4.1.5 on 2023-02-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0009_perfil_vigencia_dias_vacaciones_disp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='perfil',
            new_name='rol',
        ),
    ]
