# Generated by Django 4.1.5 on 2023-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0010_rename_perfil_perfil_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-id'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Supervisos', 'Supervisos'), ('Dueño', 'Dueño')], default='Empleado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Jovani Gonzalez', 'Jovani Gonzalez'), ('Erika Chagolla', 'Erika Gonzalez'), ('Victor Vales', 'Victor Vales'), ('Aldo', 'Aldo'), ('Jorge', 'Jorge'), ('Fransisco', 'Fransisco')], max_length=50, null=True),
        ),
    ]
