# Generated by Django 4.1.5 on 2023-02-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0011_alter_perfil_options_alter_perfil_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
