# Generated by Django 4.1.5 on 2023-02-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0012_rename_user_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('RH', 'RH'), ('Dueño', 'Dueño')], default='Empleado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Jovani Gonzalez', 'Jovani Gonzalez'), ('Erika Chagolla', 'Erika Chagolla'), ('Victor Vales', 'Victor Vales'), ('Aldo', 'Aldo'), ('Jorge', 'Jorge'), ('Fransisco', 'Fransisco')], max_length=50, null=True),
        ),
    ]
