# Generated by Django 4.1.5 on 2023-02-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0013_alter_perfil_rol_alter_solicitud_vacaciones_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
