# Generated by Django 4.1.5 on 2023-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0017_solicitud_vacaciones_nombre_alter_perfil_jefe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias_Festivos_Oficiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_festivo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitud_vacaciones',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitud vacaciones', 'verbose_name_plural': 'Solicitud vacaciones'},
        ),
    ]
