# Generated by Django 4.1.5 on 2023-02-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0018_dias_festivos_oficiales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_festivos_oficiales',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
