# Generated by Django 4.1.5 on 2023-02-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0019_dias_festivos_oficiales_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dias_festivos_oficiales',
            options={'ordering': ['-id'], 'verbose_name': 'Dia Festivo oficial', 'verbose_name_plural': 'Dias festivos oficiales'},
        ),
        migrations.AlterModelOptions(
            name='solicitud_vacaciones',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitud de vacaciones', 'verbose_name_plural': 'Solicitud de vacaciones'},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='image',
            new_name='imagen',
        ),
    ]
