# Generated by Django 4.1.5 on 2023-02-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0022_perfil_vigencia_dias_vacaciones_disp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='vigencia_dias_vacaciones_disp',
            new_name='vigencia_dias_vacaciones',
        ),
    ]
