# Generated by Django 4.1.5 on 2023-02-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0024_solicitud_vacaciones_comentario_jefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
