# Generated by Django 4.1.5 on 2023-02-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0025_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_vacaciones',
            old_name='comentario_usuario',
            new_name='comentario_solicitud',
        ),
    ]
