# Generated by Django 4.1.5 on 2023-02-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0026_rename_comentario_usuario_solicitud_vacaciones_comentario_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_jefe',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_solicitud',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
