# Generated by Django 4.1.5 on 2023-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0027_alter_solicitud_vacaciones_comentario_jefe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_jefe',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='comentario_solicitud',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
