# Generated by Django 4.1.5 on 2023-02-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0028_alter_solicitud_vacaciones_comentario_jefe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='semana',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Inglesa', 'Inglesa')], default='Normal', max_length=50, null=True),
        ),
    ]
