# Generated by Django 4.1.5 on 2023-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0031_sauce_sandwich'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='jefes',
            field=models.ManyToManyField(blank=True, related_name='jefes', to='vacaciones.jefes'),
        ),
        migrations.DeleteModel(
            name='Sandwich',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
    ]
