# Generated by Django 4.1.5 on 2023-02-25 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacaciones', '0033_alter_jefes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='jefes',
            name='nombre',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
