# Generated by Django 4.1.5 on 2023-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0034_remove_jefes_nombre_jefes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='jefes',
        ),
        migrations.RemoveField(
            model_name='jefes',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='jefe',
        ),
        migrations.AddField(
            model_name='jefes',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='jefe',
            field=models.ManyToManyField(blank=True, related_name='jefes', to='vacaciones.jefes'),
        ),
    ]
