# Generated by Django 4.1.5 on 2023-02-25 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacaciones', '0035_remove_perfil_jefes_remove_jefes_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='jefe',
            field=models.ManyToManyField(blank=True, related_name='jefes', to=settings.AUTH_USER_MODEL),
        ),
    ]
