# Generated by Django 4.1.5 on 2023-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0036_alter_perfil_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='jefe',
            field=models.ManyToManyField(blank=True, related_name='jefes', to='vacaciones.jefes'),
        ),
    ]
