# Generated by Django 4.1.5 on 2023-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0037_alter_perfil_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='jefe',
        ),
        migrations.AddField(
            model_name='perfil',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Jovani Gonzalez', 'Jovani Gonzalez'), ('Erika Chagolla', 'Erika Gonzalez'), ('Victor Valdez', 'Victor Valdez'), ('Aldo Gacía', 'Aldo Gacía'), ('Jorge Hernandez', 'Jorge Hernandez'), ('Fransisco Vargas', 'Fransisco Vargas')], max_length=50, null=True),
        ),
    ]
