# Generated by Django 4.1.5 on 2023-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0038_remove_perfil_jefe_perfil_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='jefe',
        ),
        migrations.AddField(
            model_name='perfil',
            name='jefe',
            field=models.ManyToManyField(blank=True, related_name='jefes', to='vacaciones.jefes'),
        ),
    ]
