# Generated by Django 4.1.5 on 2023-02-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0040_remove_perfil_jefe_delete_jefes_perfil_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
