# Generated by Django 4.1.5 on 2023-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0041_perfil_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('RH', 'RH'), ('Director', 'Director'), ('Dueño', 'Dueño'), ('admin', 'admin')], default='Empleado', max_length=50, null=True),
        ),
    ]
