# Generated by Django 4.1.5 on 2023-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0042_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dias_vacaciones_disp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
