# Generated by Django 4.1.5 on 2023-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0043_alter_perfil_dias_vacaciones_disp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id_asistencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
