# Generated by Django 4.1.5 on 2023-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0044_perfil_id_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Javier Ramirez', 'Javier Ramirez'), ('Yovani Gonzalez', 'Yovani Gonzalez'), ('Ivan Gonzalez', 'Ivan Gonzalez')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Supervisor', 'Supervisor'), ('Gerente', 'Gerente'), ('RH', 'RH'), ('Directivo', 'Directivo'), ('admin', 'admin')], default='Empleado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='semana',
            field=models.CharField(blank=True, choices=[('Normal', 'Lunes-Sabado'), ('Inglesa', 'Lunes-Viernes')], default='Normal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Javier Ramirez', 'Javier Ramirez'), ('Yovani Gonzalez', 'Yovani Gonzalez'), ('Ivan Gonzalez', 'Ivan Gonzalez')], max_length=50, null=True),
        ),
    ]
