# Generated by Django 4.1.5 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0046_alter_perfil_jefe_alter_perfil_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.CharField(blank=True, choices=[('Modulos', 'Modulos'), ('Mecanica', 'Mecanica'), ('Laboratorio', 'Laboratorio'), ('Administracion', 'Administracion'), ('Ventas', 'Ventas'), ('Compras', 'Compras'), ('Mantenimiento', 'Mantenimiento'), ('Cocina', 'Cocina'), ('Limpieza', 'Limpieza')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Javier Ramirez', 'Javier Ramirez'), ('Yovani Gonzalez', 'Yovani Gonzalez'), ('Ivan Gonzalez', 'Ivan Gonzalez'), ('David Mercado', 'David Mercado'), ('Aldo Garcia', 'Aldo Garcia'), ('Jorge Hernandez', 'Jorge Hernandez'), ('Francisco Vargas', 'Francisco Vargas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez', 'Javier Gonzalez'), ('Javier Ramirez', 'Javier Ramirez'), ('Yovani Gonzalez', 'Yovani Gonzalez'), ('Ivan Gonzalez', 'Ivan Gonzalez'), ('David Mercado', 'David Mercado'), ('Aldo Garcia', 'Aldo Garcia'), ('Jorge Hernandez', 'Jorge Hernandez'), ('Francisco Vargas', 'Francisco Vargas')], max_length=50, null=True),
        ),
    ]
