# Generated by Django 4.1.5 on 2023-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0049_alter_perfil_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dispositivo',
            field=models.CharField(choices=[('No registrado', 'No registrado'), ('Registrado', 'Registrado')], default='No registrado', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='semana',
            field=models.CharField(blank=True, choices=[('Lunes-Sabado', 'Lunes-Sabado'), ('Lunes-Viernes', 'Lunes-Viernes')], default='Lunes-Sabado', max_length=50, null=True),
        ),
    ]
