# Generated by Django 4.1.5 on 2023-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0050_alter_perfil_dispositivo_alter_perfil_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez Piedras', 'Javier Gonzalez Piedras'), ('Javier Gonzalez Ramirez', 'Javier Gonzalez Ramirez'), ('Yovani Gonzalez Piedras', 'Yovani Gonzalez Piedras'), ('Ivan Gonzalez Garcia', 'Ivan Gonzalez Garcia'), ('David Enrique Mercado Gonzalez', 'David Enrique Mercado Gonzalez'), ('Aldo Damian Garcia', 'Aldo Damian Garcia'), ('Jorge Roman Hernandez Cuamatla', 'Jorge Roman Hernandez Cuamatla'), ('Francisco Javier Vargas Ojeda', 'Francisco Javier Vargas Ojeda'), ('Erika Paola Chagolla Gonzalez', 'Erika Paola Chagolla Gonzalez'), ('Mario Alberto Mejia Contador', 'Mario Alberto Mejia Contador')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_vacaciones',
            name='jefe',
            field=models.CharField(blank=True, choices=[('Javier Gonzalez Piedras', 'Javier Gonzalez Piedras'), ('Javier Gonzalez Ramirez', 'Javier Gonzalez Ramirez'), ('Yovani Gonzalez Piedras', 'Yovani Gonzalez Piedras'), ('Ivan Gonzalez Garcia', 'Ivan Gonzalez Garcia'), ('David Enrique Mercado Gonzalez', 'David Enrique Mercado Gonzalez'), ('Aldo Damian Garcia', 'Aldo Damian Garcia'), ('Jorge Roman Hernandez Cuamatla', 'Jorge Roman Hernandez Cuamatla'), ('Francisco Javier Vargas Ojeda', 'Francisco Javier Vargas Ojeda'), ('Erika Paola Chagolla Gonzalez', 'Erika Paola Chagolla Gonzalez'), ('Mario Alberto Mejia Contador', 'Mario Alberto Mejia Contador')], max_length=50, null=True),
        ),
    ]
