# Generated by Django 4.1.5 on 2023-07-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0051_alter_perfil_jefe_alter_solicitud_vacaciones_jefe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='dispositivo',
        ),
    ]
