# Generated by Django 4.1.5 on 2023-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='idUser',
            field=models.CharField(choices=[('3', 'JessicaZuniga'), ('5', 'AraceliZuniga'), ('6', 'ErikaChagolla')], max_length=50),
        ),
    ]
