# Generated by Django 4.1.5 on 2023-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='idUser',
            field=models.IntegerField(choices=[(3, 'JessicaZuniga'), (5, 'AraceliZuniga'), (6, 'ErikaChagolla')]),
        ),
    ]
