# Generated by Django 4.1.5 on 2023-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_asistencia_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
