# Generated by Django 4.1.5 on 2023-05-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_asistencia_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='nombre',
        ),
    ]
