# Generated by Django 4.1.5 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asistenciaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(unique=True)),
            ],
            options={
                'verbose_name': 'asistenciaQR',
                'verbose_name_plural': 'asistenciasQR',
                'ordering': ['-id'],
            },
        ),
    ]
