# Generated by Django 4.1.5 on 2023-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistenciaQR', '0003_alter_asistenciaqr_fecha_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaqr',
            options={'ordering': ['-id'], 'verbose_name': 'AsistenciaQR', 'verbose_name_plural': 'AsistenciasQR'},
        ),
    ]
