# Generated by Django 4.1.5 on 2023-07-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0052_alter_perfil_options_remove_perfil_dispositivo'),
        ('asistenciaQR', '0004_alter_asistenciaqr_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(choices=[('No registrado', 'No registrado'), ('Registrado', 'Registrado')], default='No registrado', max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('pantalla', models.CharField(blank=True, max_length=50, null=True)),
                ('agente', models.CharField(blank=True, max_length=200, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('nucleos', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='vacaciones.perfil')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-id'],
            },
        ),
    ]
