# Generated by Django 4.1.5 on 2023-07-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0052_alter_perfil_options_remove_perfil_dispositivo'),
        ('asistenciaQR', '0006_rename_dispositivo_dispositivo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='vacaciones.perfil'),
        ),
    ]
